server:
  port: 8085

spring:
  cloud:
    gateway:
      routes:
        - id: company_route
          uri: ${INVOICE_SERVICE_URL}/v1/company-vats
          predicates:
            - Path=/v1/company-vats/**
  rabbitmq:
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}