server:
  port: 8085
  servlet:
    contextPath: /api

spring:
  cloud:
    gateway:
      routes:
        - id: company_route
          uri: https://invoice-service.railway.internal/company-vats
          predicates:
            - Path=/company-vats/**
  rabbitmq:
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}